Finally fixing refreshNode
ioBroker/ioBroker.zwave pull request #62
Opened 2019-08-14 06:20 UTC by cburghardt

Previous version was buggy (calcName expects other values)

2019-08-14 10:05 UTC, AlCalzone requested changes
Two minor things, looks good otherwise.

2019-08-14 10:05 UTC, AlCalzone commented on main.js
> +        var id = calcName(nodeID, comClass);
please use `const`

2019-08-14 10:05 UTC, AlCalzone commented on main.js
> +            if (i.substring(0, id.length + 1) === id + '.' || i === id) {
`if (i.startsWith(id + '.') || i === id) {`

2019-08-14 10:10 UTC, cburghardt commented
done. Please also bump the version, thanks.

2019-08-14 10:30 UTC, AlCalzone approved these changes

2019-08-14 10:30 UTC, merged

2019-08-14 10:38 UTC, AlCalzone commented
Released as v1.5.1

2019-08-18 21:35 UTC, OleksiyAntonov commented
Do you have plans to update official repo with this version?

2019-08-18 23:01 UTC, Apollon77 commented
1.5.1 should be in latest in the meantime. Stable is updated after enough users use this version and somit can be considered stable.