Network map
ioBroker/ioBroker.zwave pull request #69
Opened 2019-08-25 14:12 UTC by cburghardt

Implement a network map in a separate tab.
Uses the vis network library (loaded from remote).

2019-08-25 18:50 UTC, AlCalzone commented
Care to post a screenshot here? I'm curious but I only have a production system with Z-Wave.

2019-08-25 18:53 UTC, AlCalzone requested changes

2019-08-25 18:53 UTC, AlCalzone commented on admin/i18n/de/translations.json
> +    "Associations": "Verbände",
"Verknüpfungen" ist besser

2019-08-25 18:53 UTC, AlCalzone commented on admin/i18n/de/translations.json
> +    "Network map": "Netzwerkkarte",
Vielleicht besser "Netzwerk-Übersicht"? Netzwerkkarte klingt mir sehr nach der Hardware, die sich in meinem PC befindet.

2019-08-25 18:53 UTC, AlCalzone commented on admin/index.html
> +<link href="https://unpkg.com/vis-network@latest/dist/vis-network.min.css" rel="stylesheet" type="text/css" />
That should be included locally (same for the js file). Just put it in the admin dir and reference it from there.

2019-08-25 18:53 UTC, AlCalzone commented on main.js
> +                                adapter.log.debug(nodeID+"="+JSON.stringify(item));
remove debug log please

2019-08-25 19:22 UTC, cburghardt commented
![Bildschirmfoto 2019-08-25 um 21 04 40](https://user-images.githubusercontent.com/839480/63654703-5ce79b80-c77e-11e9-9117-1d2bc3a8f156.jpg)

2019-08-25 19:25 UTC, cburghardt commented
I just erased some labels. My map is pretty busy as it is production as well.
It uses the same network graphing as the zigbee adapter.

2019-08-25 20:39 UTC, Apollon77 commented
Cool

2019-08-26 06:29 UTC, AlCalzone commented
That looks wild :D

2019-08-26 06:30 UTC, merged