translations and minor layout fixes
ioBroker/ioBroker.zwave pull request #71
Opened 2019-08-28 07:06 UTC by cburghardt

- association selects are missing translations
- network map tries to load the js.map (can be seen as 404 in the browser)
- reduce size of network map a bit so that it fits
- sort devices by node ID so that the sequence is correct. If you currently refresh a device it is removed and added again, jumping to the end of the list although it might have a lower node ID

2019-08-28 08:44 UTC, AlCalzone requested changes

2019-08-28 08:44 UTC, AlCalzone commented on admin/i18n/de/translations.json
> +    "Select group": "Gruppe wählen",
Um konsistent zu bleiben:
```suggestion
    "Select group": "Gruppe auswählen",
```

words.js nicht vergessen!

2019-08-28 08:44 UTC, AlCalzone commented on admin/index.html
> +            });
Ich mag Arrow-Functions mit return nicht, wenns auch als Einzeiler geht.
```js
_devices.rows.sort((a, b) => (a.value.native.nodeID < b.value.native.nodeID ? -1 : 1));
```

2019-08-28 08:44 UTC, AlCalzone commented on admin/index.html
> +                                    $('#assGroups').append($("<option>").attr("disabled", "disabled").text(_('Select group'))).selectmenu('refresh');
Das braucht einen Kommentar

2019-08-28 08:57 UTC, cburghardt commented on admin/i18n/de/translations.json
> +    "Select group": "Gruppe wählen",
done

2019-08-28 08:57 UTC, cburghardt commented on admin/index.html
> +            });
done

2019-08-28 08:57 UTC, cburghardt commented on admin/index.html
> +                                    $('#assGroups').append($("<option>").attr("disabled", "disabled").text(_('Select group'))).selectmenu('refresh');
done

2019-08-28 10:00 UTC, AlCalzone approved these changes

2019-08-29 12:10 UTC, cburghardt commented
@AlCalzone when you merge that could you also bump up the version?

2019-09-02 07:15 UTC, cburghardt commented
When will that PR be merged?

2019-09-04 20:36 UTC, GermanBluefox commented
@AlCalzone LGTM ?

2019-09-05 07:02 UTC, merged